---
- name: Download docker images
  hosts: all
  tasks:
   - name: Pulling of images
     docker_image:
      name: "{{item}}"
     with_items:
      - mysql
      - httpd
      - postgres
      - nginx

