---
- name: Setup of jenkins and tomcat container for CI-CD using Docker-Ansible
  hosts: all
  tasks:
   - name: Start a jenkins container
     docker_container:
      image: jenkins
      name: jenkinsserver
      ports:
       - 5050:8080
   - name: Start tomcat as QAServer and ProdServer
     docker_container:
      image: tomcat
      name: "{{item.a}}"
      ports:
       - "{{item.b}}"
      links:
       - jenkinsserver:jenkins
     with_items:
      - {a: qaserver,b: "6060:8080"}
      - {a: prodserver,b: "7070:8080"}
