---
- name: Implementing docker compose using ansible
  hosts: all
  tasks:
   - name: Start mysql container
     docker_container:
      image: mysql:5
      name: mydb
      env:
       MYSQL_ROOT_PASSWORD: intelliqit
   - name: Start wordpress container
     docker_container:
      image: wordpress
      name: mywordpress
      ports:
       - "8888:80"
      links:
       - mydb:mysql
...

